// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhogawlpuejlboorentf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRob2dhd2xwdWVqbGJvb3JlbnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTkxMzgsImV4cCI6MjA2NTU5NTEzOH0.iTz87bZE75TbVHNdhwwfpfGe5TXV6iIfhnXvKY8_O8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);